#!/usr/bin/perl -w

use v5.26.0;

use warnings;

use lib qw(/ams/texmf/texml/lib/perl);

use TeX::FMT::File;

use open qw(:std :encoding(UTF-8));

my $file   = shift || 'plain.fmt';
my $tlyear = shift || '2016';

my $fmt = TeX::FMT::File->new({ file_name => $file });

$fmt->set_tlyear($tlyear);

print qq{*** tlyear = }, $fmt->tlyear(), "\n\n";

$fmt->open('r');

$fmt->load();

# $fmt->debug();

print "engine: ", $fmt->get_engine(), "\n";
print "active_base: ", $fmt->active_base(), "\n";
print "undefined_control_sequence: ", $fmt->undefined_control_sequence(), "\n";
print "null: ", $fmt->null(), "\n";

print "\n";

# print "frozen_dont_expand: ", $fmt->frozen_dont_expand, "\n";
# print "frozen_null_font: ", $fmt->frozen_null_font, "\n";
# print "frozen_primitive: ", $fmt->frozen_primitive, "\n";
# print "prim_eqtb_base: ", $fmt->prim_eqtb_base, "\n";
# print "undefined_control_sequence: ", $fmt->undefined_control_sequence, "\n";
# 
# print "\n";
# 
# print "del_code_base = ", $fmt->del_code_base, "\n";
# 
# print "\n";

#exit;

my $eqtb = $fmt->get_eqtb();
my $hash = $fmt->get_hash();

# Region 1: active_base..null_cs
# Region 2: hash_base..undefined_control_sequence

for my $ptr ($fmt->active_base()..$fmt->undefined_control_sequence()) {
    my $word = $eqtb->get_word($ptr);

    next if $word->get_type() == $fmt->undefined_cs;

    my $name;

    if ($ptr < $fmt->single_base) {
        $name = chr($ptr - 1);
    } elsif ($ptr < $fmt->null_cs()) {
        $name = "\\" . chr($ptr - $fmt->single_base);
    } else {
        my $string_no = $hash->get_text($ptr);

        if (defined $string_no) {
            $name = $fmt->get_string($string_no);
        } else {
            $name = '<undef>';
        }

        # Ignore various language-related macros.
        next if $name =~ m{^(lang|lhm|rhm)\@};

        $name = qq{\\$name};
    }

    print $ptr, ": ", $name, ": ";
    $fmt->show_eqtb_entry($ptr);
}

__END__
