#!/usr/bin/perl -w

use strict;
use warnings;

use version; our $VERSION = qv '0.0.0';

my %MACRO = (
    PASCAL => 'Pascal',
    eTeX   => 'eTeX',
    TeX    => 'TeX',
    pdfTeX => 'pdfTeX',
    TeXeT  => 'TeX-XeT',
    TeXXeT => 'TeX--XeT',
    PDF    => 'PDF',
    ph     => 'Pascal-H',
    MF     => 'METAFONT',
    glob   => '13',
    gglob  => '20, 26',
    AM     => '&',
    pct    => '%',
);

sub sanitize( $ ) {
    my $string = shift;

    $string =~ s{\\(.)}{$1}g;

    return $string;
}

while (<>) {
    m{^% Here is TeX material that gets inserted after} and do {
        while (<>) {
            last if m{^\@\*};
        }
    };

    s{\A \@\* \ \\}{\@* }smx and do {
        print;

        print "\n";

        while (<>) {
            last if m{\S};
        }
    };

    # Strip index entries
    m{\A \s* (\@!)? \@[:.^].*?\@> \s* \z}smx and next;

    s{\\[.\\&]\{(.*?)\}}{ sanitize($1) }eg;

    s{\\\.}{}g;

    s{\\\(.*?\)}{}g;

    s{\\(\w+)\\?}{ $MACRO{$1} || "\\$1" }eg;

    print;
}

__END__
