%%
%% This is file `mmono-s.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% mmono-s.dtx 
%% 
%%% ====================================================================
%%% @LaTeX-file{
%%%   filename  = "mmono-s.dtx",
%%%   version   = "1.1b",
%%%   date      = "1998/04/13",
%%%   time      = "14:31:13",
%%%   checksum  = "63609 101 422 3387",
%%%   author    = "American Mathematical Society",
%%%   copyright = "Copyright (C) 1998 American Mathematical Society,
%%%                all rights reserved.  Copying of this file is
%%%                authorized only if either:
%%%                (1) you make absolutely no changes to your copy,
%%%                including name; OR
%%%                (2) if you do make changes, you first rename it
%%%                to some other name.",
%%%   address   = "American Mathematical Society,
%%%                Technical Support,
%%%                Electronic Products and Services,
%%%                P. O. Box 6248,
%%%                Providence, RI 02940,
%%%                USA",
%%%   telephone = "401-455-4080 or (in the USA and Canada)
%%%                800-321-4AMS (321-4267)",
%%%   FAX       = "401-331-3842",
%%%   email     = "tech-support@ams.org (Internet)",
%%%   supported = "yes",
%%%   keywords  = "",
%%%   abstract  = "LaTeX documentclass for Mathematical Monographs
%%%                (Japanese/Iwanami) Subseries.",
%%%   docstring = "The checksum field above contains: CRC-16
%%%     checksum, number of lines, number of words, and number of
%%%     characters, as produced by Robert Solovay's checksum utility.",
%%% }
%%% ====================================================================
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{mmono-s}[1998/04/13 v1.1b]
\DeclareOption*{\PassOptionsToClass{\CurrentOption}{amsbook}}
\ProcessOptions
\LoadClass{amsbook}[1996/10/24]
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\textheight=42pc \textwidth=25pc \calclayout
\endinput %
\endinput
%%
%% End of file `mmono-s.cls'.
